if(NOT DEFINED CLI OR NOT DEFINED WORK)
  message(FATAL_ERROR "CLI and WORK are required")
endif()
# Invalid choices must retry; choosing the first legal action must finish a game.
string(REPEAT "1\n" 256 choices)
file(WRITE "${WORK}/cli-input.txt" "oops\n0\n999\n${choices}")
foreach(seat IN ITEMS 0 1)
  foreach(bot IN ITEMS random heuristic)
    set(replay "${WORK}/human-${seat}-${bot}.json")
    execute_process(COMMAND "${CLI}" play --seed 42 --human "${seat}" --bot "${bot}" --save "${replay}"
      INPUT_FILE "${WORK}/cli-input.txt" RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 10)
    if(NOT status EQUAL 0 OR NOT output MATCHES "wins\\.|Draw:" OR NOT output MATCHES "Enter a listed action number" OR output MATCHES "ended early")
      message(FATAL_ERROR "Human CLI game failed: ${status}\n${output}\n${error}")
    endif()
    execute_process(COMMAND "${CLI}" replay --file "${replay}" RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 10)
    if(NOT status EQUAL 0 OR NOT output MATCHES "Replay verified")
      message(FATAL_ERROR "Human replay failed: ${status}\n${output}\n${error}")
    endif()
  endforeach()
endforeach()
file(WRITE "${WORK}/cli-quit.txt" "q\n")
execute_process(COMMAND "${CLI}" play --seed 42 INPUT_FILE "${WORK}/cli-quit.txt"
  RESULT_VARIABLE status OUTPUT_VARIABLE output TIMEOUT 10)
if(NOT status EQUAL 0 OR NOT output MATCHES "ended early")
  message(FATAL_ERROR "Quit did not end cleanly")
endif()
