execute_process(COMMAND "${GODOT}" --headless --editor --path "${CLIENT}" --import --log-file "${WORK}/godot-import.log" RESULT_VARIABLE imported OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 120)
if(NOT imported EQUAL 0 OR "${output}${errors}" MATCHES "SCRIPT ERROR|Parse Error")
  message(FATAL_ERROR "Godot import failed: ${imported}\n${output}\n${errors}")
endif()
execute_process(COMMAND "${GODOT}" --headless --path "${CLIENT}" --script res://tests/offline_checks.gd --log-file "${WORK}/godot-tests.log" -- "${FIXTURE}" "${WORK}" RESULT_VARIABLE checked OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 120)
if(NOT checked EQUAL 0 OR "${output}${errors}" MATCHES "SCRIPT ERROR|Parse Error|ERROR:")
  message(FATAL_ERROR "Godot checks failed: ${checked}\n${output}\n${errors}")
endif()
message(STATUS "${output}")
file(GLOB replays "${WORK}/m3-*.json")
list(LENGTH replays count)
if(NOT count EQUAL 32)
  message(FATAL_ERROR "Expected 32 client replays, found ${count}")
endif()
foreach(replay IN LISTS replays)
  execute_process(COMMAND "${CLI}" replay --file "${replay}" RESULT_VARIABLE verified OUTPUT_VARIABLE output ERROR_VARIABLE errors)
  if(NOT verified EQUAL 0)
    message(FATAL_ERROR "Headless parity failed: ${replay}\n${output}\n${errors}")
  endif()
endforeach()
message(STATUS "All 32 client replays pass headless execution and expected-result verification")
